services:
  - type: web
    name: sentiment-api
    runtime: python
    buildCommand: ""
    startCommand: uvicorn extractor:app --host 0.0.0.0 --port 10000 
    #extractor:app = fichier extractor.py contenant une variable app = FastAPI()
    envVars: []
